config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
      get 'search_tag'
      get 'search_item'
    end
  end
  resources :addresses, only: [:new, :create]
  resources :cards, only: [:new, :create]
  resources :users, only: :show
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to :status
  belongs_to :category
  belongs_to :shipping_fee_status
  belongs_to :prefecture
  belongs_to :scheduled_delivery
  has_many_attached :images
  has_many :item_tag_relations, dependent: :destroy
  has_many :tags, through: :item_tag_relations
  has_many :comments
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model

  attr_accessor(
    :name, :price, :info, :status_id, :category_id, :shipping_fee_status_id,
    :prefecture_id, :scheduled_delivery_id, :images, :user_id, :id, :created_at,
    :datetime, :updated_at, :datetime, :tag_name
  )

  with_options presence: true do
    validates :name
    validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }
    validates :info
    validates :status_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :category_id, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10, message: 'を選択してください' }
    validates :shipping_fee_status_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :prefecture_id, numericality: { other_than: 0, message: 'を選択してください' }
    validates :scheduled_delivery_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :images, length: { minimum: 1, maximum: 5, message: 'は1枚以上5枚以下にしてください' }
  end

  def save
    item = Item.create(
      name: name, price: price, info: info, status_id: status_id, category_id: category_id,
      shipping_fee_status_id: shipping_fee_status_id, prefecture_id: prefecture_id,
      scheduled_delivery_id: scheduled_delivery_id, images: images, user_id: user_id
    )
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    ItemTagRelation.create(item_id: item.id, tag_id: tag.id)
  end

  def update(params, item)
    item.item_tag_relations.destroy_all

    tag_name = params.delete(:tag_name)

    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?

    tag.save if tag_name.present?
    item.update(params)
    ItemTagRelation.create(item_id: item.id, tag_id: tag.id) if tag_name.present?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_login, except: [:index, :show]
  before_action :item_finding, only: [:show, :edit, :update, :destroy]

  def index
    @items_list = Item.all.order('created_at DESC')
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  def new
    @item_form = ItemForm.new
  end

  def create
    @item_form = ItemForm.new(item_form_params)
    if @item_form.valid?
      @item_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @q = Item.ransack(params[:q])
    @items = @q.result

    @comments = @item.comments.includes(:user)
    @comment = Comment.new

    all_item_id = Item.pluck(:id)
    now_item = all_item_id.index(@item.id)
    @next_item_id = all_item_id[now_item + 1]
    @before_item_id = all_item_id[now_item - 1]
    @limit_high = all_item_id.max
    @item_id_low = all_item_id[0]
  end

  def edit
    redirect_to root_path if @item.user.id != current_user.id || Order.exists?(item_id: @item.id)
    item_attributes = @item.attributes
    @item_form = ItemForm.new(item_attributes)
    @item_form.tag_name = @item.tags&.first&.tag_name
  end

  def update
    @item_form = ItemForm.new(item_form_params)

    @item_form.images ||= @item.images.blobs
    if @item_form.valid?
      @item_form.update(item_form_params, @item)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    if @item.user_id == current_user.id
      @item.destroy
      redirect_to root_path
    end
  end

  def search_tag
    return nil if params[:keyword] == ''

    tag = Tag.where(['tag_name LIKE?', "%#{params[:keyword]}%"])
    render json: { keyword: tag }
  end

  def search_item
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(' ')
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  private

  def item_form_params
    params.require(:item_form).permit(
      :name, :price, :info, :status_id, :category_id, :shipping_fee_status_id,
      :prefecture_id, :scheduled_delivery_id, :tag_name, { images: [] }
    ).merge(user_id: current_user.id)
  end

  def item_finding
    @item = Item.find(params[:id])
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>
    
    <ul class='item-lists'>
        <% @items_list.each do |item| %>
          <li class='list'>
            <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <% if item.images.present? %>
                <%= image_tag item.images[0], class: "item-img" %>
              <% end %>
              <% if Order.exists?(item_id: item.id) %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
              <% end %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br><%= item.shipping_fee_status.name %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
            <% end %>
          </li>
        <% end %>
      
      <% if !@items.exists? %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              商品を出品してね！
            </h3>
            <div class='item-price'>
              <span>99999999円<br>(税込み)</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>  
      
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to new_item_path, class: 'purchase-btn' do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item_form, url: items_path, method: :post, id: "item_image_preview", local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <div id="previews", class="previews" ></div>
        <%= f.file_field :images, class:"img-button", id:"item-image", name: 'item_form[images][]', data: {index: 0} %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          タグ
        </div>
        <%= f.text_area :tag_name, class:"items-tag", id:"item-tag", placeholder:"商品のタグ", maxlength:"20" %>
        <div id="search-result"></div>
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_status_id, ShippingFeeStatus.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/search_item.erb
<%= render "shared/header" %>

<div class='item-contents' id="detailed-search-result-wrapper">
  <div class='search-flex'>
    <%= search_form_for @q, url: search_item_items_path, html: {id: "detailed-search-form"} do |f| %>
      <div class="search-field">
        <%= f.label :name, '商品名' %>
        <br>
        <%= f.text_field :name, value: params[:q]&.dig(:name) %>
      </div>
      <div class="search-field">
        <%= f.label :user_nickname_cont, '出品者名' %>
        <br>
        <%= f.text_field :user_nickname_cont %>
      </div>
      <div class="search-field">
        <%= f.label :category_id_in, 'カテゴリ' %>
        <br>
        <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name, {include_blank: "---"}) %>
      </div>
      <div class="search-field">
        <%= f.label :price_gteq, '価格'%>
        <br>
        <%= f.number_field :price_gteq %> 円以上
        <br>
        <%= f.number_field :price_lteq %> 円以下
      </div>
      <%= f.submit '検索' %>
    <% end %>
    <ul class='item-lists' id="detailed-search-result">
      <% @items.each do |item| %>  
        <% unless Order.exists?(item_id: item.id) %>
          <li class='list'>
            <div class="posted-content">
              <% if item.images.present? %>
                <%= image_tag item.images[0], class: "item-img" %><br>
              <% end %>
              <%= item.name%><br>
              <%= link_to '詳細', item_path(item.id)%>
            </div>
          </li>
        <% end %>      
      <% end %>
    </ul>
  </div>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.images[0] ,class:"item-box-img" %>
      <div class="other-images">
        <% @item.images[1..-1].each do |image| %>
          <div class="other-image">
            <%= image_tag image, class:"mini_image" %>
          </div>
        <% end %>
      </div>
      <% if Order.exists?(item_id: @item.id) %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%= @item.price %>
      </span>
      <span class="item-postage">
        <%= @item.shipping_fee_status.name %>
      </span>
    </div>
    <% unless Order.exists?(item_id: @item.id) %>
      <% if user_signed_in? && @item.user_id == current_user.id %>
        <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <% end %>
      <% if user_signed_in? && @item.user_id != current_user.id %>
        <%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value">
            <%= link_to @item.user.nickname, user_path(@item.user_id), class:"user-link" %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @item.tags&.first&.tag_name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.scheduled_delivery.name %></td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? %>
      <div class="option">
        <div class="favorite-btn">
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <span>お気に入り 0</span>
        </div>
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な商品の通報</span>
        </div>
      </div>
    <% end %>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">

    <div id="comments-index">
      <h4>＜コメント一覧＞</h4>
      <% @item.comments.each do |comment|%>
        <div class="comment">
          <p class="user-info"><%= comment.user.nickname %>: <%= comment.text %></p>
        </div>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <%= form_with model: [@item, @comment], url: item_comments_path(@item.id), method: :post, id:"comment-form" do |f| %>
        <%= f.text_area :text, class:"comment-text", placeholder:"相手のことを考え丁寧なコメントを心がけましょう。\n不快な言葉遣いなどは利用制限や退会処分となることがあります。"  %>
        <div class="comment-btn">
          <%= f.submit "コメントする",class:"comment-submit" %>
        </div>
      <% end %>
    <% end %>

  </div>
  <div class="links">
  <% if @item.id != @limit_high %>
    <%= link_to "⏪次の商品", item_path(@next_item_id), method: :get, class: "change-item-btn" %>
    <% else %>
    <div class="blank"></div>
  <% end %>
  <% if @item.id != @item_id_low  %>
    <%= link_to "前の商品⏩", item_path(@before_item_id), method: :get, class: "change-item-btn" %>
  <% end %>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>