config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
      get 'search_tag'
      get 'search_item'
    end
  end
  resources :addresses, only: [:new, :create]
  resources :cards, only: [:new, :create]
  resources :users, only: :show
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :card_token

  validates :card_token, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:card_token]
    )
    card = Card.new(
      card_token: params[:card_token],
      customer_token: customer.id,
      user_id: current_user.id
    )

    if card.save
      redirect_to root_path
    else
      redirect_to action: 'new'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'charge-form', class: 'card-form', local: true do |f| %>
  <%# カード情報の入力 %>
  <div class='credit-card-form'>
    <h1 class='info-input-haedline'>
      クレジットカード情報入力
    </h1>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">カード情報</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
      <div class='available-card'>
        <%= image_tag 'card-visa.gif', class: 'card-logo'%>
        <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
        <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
        <%= image_tag 'card-amex.gif', class: 'card-logo'%>
      </div>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">有効期限</label>
        <span class="indispensable">必須</span>
      </div>
      <div class='input-expiration-date-wrap'>
        <%= f.select :exp_month, 1..12, {include_blank: "---"}, class:"input-expiration-date", id:"card-exp-month" %>
        <p>月</p>
        <%= f.select :exp_year, 22..27, {include_blank: "---"}, class:"input-expiration-date", id:"card-exp-year" %>
        <p>年</p>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">セキュリティコード</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
    </div>
  </div>
  <%= f.submit "登録する" , class:"card-button" , id:"button" %>
  <%= link_to "戻る", root_path, class:"back-button"%>
  <%# /カード情報の入力 %>
<% end %>